# Logging Configuration
# Python logging configuration for GDP evaluation framework

version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - [%(filename)s:%(lineno)d] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  json:
    format: '%(asctime)s'
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/gdpval.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
    encoding: utf-8

  evaluation_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: logs/evaluation.log
    maxBytes: 52428800  # 50MB
    backupCount: 10
    encoding: utf-8

loggers:
  src.evaluation:
    level: INFO
    handlers: [console, evaluation_file]
    propagate: false

  src.metrics:
    level: DEBUG
    handlers: [file]
    propagate: false

  src.models:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.providers:
    level: INFO
    handlers: [console, file]
    propagate: false

  src.analysis:
    level: INFO
    handlers: [console, file]
    propagate: false

  vllm:
    level: WARNING
    handlers: [file]
    propagate: false

  transformers:
    level: WARNING
    handlers: [file]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]

# Performance logging settings
performance:
  log_gpu_metrics: true
  log_memory_usage: true
  log_inference_time: true
  metrics_interval_seconds: 60

# Development vs Production
environments:
  development:
    console_level: DEBUG
    file_level: DEBUG
    verbose: true

  production:
    console_level: INFO
    file_level: WARNING
    verbose: false

  testing:
    console_level: ERROR
    file_level: DEBUG
    verbose: false